### ISSUE TITLE
Implement FHIR model deploy process

### ISSUE THREAD

**Issue by znatty22** [d3b-center/clinical-data-flow#87]
Upon successful execution of the integration tests and completion of a model release, the FHIR model should be deployed to the production server.

Issue for it is here: 
https://github.com/kids-first/kf-model-fhir/issues/143

Depends on: 

- [x] Implementation of FHIR model release implementation https://github.com/kids-first/kf-model-fhir/issues/118
- [x] Implementation of integration tests https://github.com/kids-first/kf-model-fhir/issues/147
- [ ] Update canonical URL to prod URL https://github.com/kids-first/kf-model-fhir/issues/146
- [ ] Ensure all resources have standard attributes https://github.com/kids-first/kf-model-fhir/issues/92
